# Generated by Django 3.2.4 on 2021-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_reciever', '0002_alter_videos_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={},
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
