# Generated by Django 3.2.4 on 2021-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_reciever', '0003_auto_20210621_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
